// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
    NEXT_PUBLIC_SUPABASE_URL:string,
    NEXT_PUBLIC_SUPABASE_ANON_KEY:string,
    NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME:string,
    NEXT_PUBLIC_CLOUDINARY_API_KEY:string,
    NEXT_PUBLIC_CLOUDINARY_API_SECRET:string,
}
